activation: gelu
alias: null
attn_dropout: 0.0
batch_normalization: false
batch_size: 32
drop_last_loader: false
dropout: 0.1
early_stop_patience_steps: -1
encoder_layers: 3
exclude_insample_y: false
fc_dropout: 0.1
futr_exog_list: null
h: 24
head_dropout: 0.0
hidden_size: 128
hist_exog_list: null
inference_windows_batch_size: 1024
input_size: 168
learn_pos_embed: true
learning_rate: 0.001
linear_hidden_size: 256
loss: !!python/object:neuralforecast.losses.pytorch.MSE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
max_steps: 5000
n_heads: 4
num_lr_decays: -1
num_workers_loader: 0
patch_len: 16
random_seed: 42
res_attention: true
revin: true
revin_affine: false
revin_subtract_last: true
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 1
stride: 8
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
